config/routes.rb
AmoebaCircusOnRailsRuby003::Application.routes.draw do
  resources :acts
  resources :performers

  get 'performers/:id/split' => 'performers#split', :as => 'split_performer'

  get '/index' => 'dashboard#index'
  get '/index/performers/:id/move' => 'performers#move', as: 'move_performer' 
  post '/index/performers/:id/move' => 'performers#move_act'

  

end

app/models/act.rb
class Act < ActiveRecord::Base
  has_many :act_performers
  has_many :performers, :through => :act_performers
end

app/models/act_performer.rb
class ActPerformer < ActiveRecord::Base
  belongs_to :performer
  belongs_to :act
end

app/models/performer.rb
class Performer < ActiveRecord::Base
  has_many :act_performers
  has_many :acts, :through => :act_performers
  belongs_to :talent
end

app/models/talent.rb
class Talent < ActiveRecord::Base
  has_many :talents
end

app/controllers/acts_controller.rb
class ActsController < ApplicationController
  before_action :set_act, only: [:show, :edit, :update, :destroy]

  # GET /acts
  # GET /acts.json
  def index
    @acts = Act.all
  end

  # GET /acts/1
  # GET /acts/1.json
  def show
  end

  # GET /acts/new
  def new
    @act = Act.new
  end

  # GET /acts/1/edit
  def edit
  end

  # POST /acts
  # POST /acts.json
  def create
    @act = Act.new(act_params)
    if params[:performer]
      params[:performer].each do |performer_id|
        @act.act_performers.build(:performer_id => performer_id.to_i)
      end
    else
    end
    respond_to do |format|
      if @act.save
        format.html { redirect_to @act, notice: 'Act was successfully created.' }
        format.json { render action: 'show', status: :created, location: @act }
      else
        format.html { render action: 'new' }
        format.json { render json: @act.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acts/1
  # PATCH/PUT /acts/1.json
  def update
    @act.performers.clear
    if params[:performer]
      params[:performer].each do |performer_id|
        @act.act_performers.build(:performer_id => performer_id.to_i)
      end
    else
    end

    respond_to do |format|
      if @act.update(act_params)
        format.html { redirect_to @act, notice: 'Act was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @act.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acts/1
  # DELETE /acts/1.json
  def destroy
    @act.destroy
    respond_to do |format|
      format.html { redirect_to acts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_act
      @act = Act.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def act_params
      params.require(:act).permit(:name, :date, :time)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @acts = Act.all
    @performers = Performer.all
  end

end

app/controllers/performers_controller.rb
class PerformersController < ApplicationController
  before_action :set_performer, only: [:show, :edit, :update, :split, :move, :move_act, :destroy]

  # GET /performers
  # GET /performers.json
  def index
    @performers = Performer.all
  end

  # GET /performers/1
  # GET /performers/1.json
  def show
  end

  # GET /performers/new
  def new
    @performer = Performer.new
    @talent = Talent.new
  end

  # GET /performers/1/edit
  def edit
  end

  # POST /performers
  # POST /performers.json
  def create
    @performer = Performer.new(performer_params)
    @talent = Talent.find_or_create_by(:name => params[:performer][:talent])
    @performer.talent = @talent
    if params[:act]
      params[:act].each do |act_id|
        @performer.act_performers.build(:act_id => act_id)
      end
    else
    end

    respond_to do |format|
      if @performer.save
        format.html { redirect_to @performer, notice: 'Performer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @performer }
      else
        format.html { render action: 'new' }
        format.json { render json: @performer.errors, status: :unprocessable_entity }
      end
    end
  end

  def move
  end


  def move_act
    @performer.acts.clear
    if params[:act]
      params[:act].each do |act_id|
        @performer.act_performers.build(:act_id => act_id)
      end
    else
    end
    redirect_to index_path if @performer.save

  end

  # PATCH/PUT /performers/1
  # PATCH/PUT /performers/1.json
  def update
    @talent = Talent.find_or_create_by(:name => params[:performer][:talent])
    @performer.talent = @talent
    @performer.acts.clear
    if params[:act]
      params[:act].each do |act_id|
        @performer.act_performers.build(:act_id => act_id)
      end
    else
    end

    respond_to do |format|
      if @performer.update(performer_params)
        format.html { redirect_to @performer, notice: 'Performer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @performer.errors, status: :unprocessable_entity }
      end
    end
  end

  def split
    Performer.create([{:name => @performer.name, :talent => @performer.talent, :generation_number => @performer.generation_number + 1},{:name => @performer.name,:talent => @performer.talent, :generation_number => @performer.generation_number + 1} ])
    @performer.destroy
    respond_to do |format|
      format.html { redirect_to performers_url }
      format.json { head :no_content }
    end
  end


  # DELETE /performers/1
  # DELETE /performers/1.json
  def destroy
    @performer.destroy
    respond_to do |format|
      format.html { redirect_to performers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_performer
      @performer = Performer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def performer_params
      params.require(:performer).permit(:name, :generation_number)
    end
end

app/helpers/acts_helper.rb
module ActsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/performers_helper.rb
module PerformersHelper
end

app/views/acts/_form.html.erb
<%= form_for(@act) do |f| %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :time %><br>
    <%= f.time_select :time %>
  </div>

  <% Performer.all.each do |p| %>
  <div class="checkbox"> 
    <%= check_box_tag('performer[]', p.id, p.acts.include?(@act), :id => p.name ) %>
    <%= label_tag p.name %>
  </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/acts/edit.html.erb
<h1>Editing act</h1>

<%= render 'form' %>

<%= link_to 'Show', @act %> |
<%= link_to 'Back', acts_path %>

app/views/acts/index.html.erb
<h1>Listing acts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Time</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @acts.each do |act| %>
      <tr>
        <td><%= act.name %></td>
        <td><%= act.date %></td>
        <td><%= act.time %></td>
        <td><%= link_to 'Show', act %></td>
        <td><%= link_to 'Edit', edit_act_path(act) %></td>
        <td><%= link_to 'Destroy', act, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Act', new_act_path %>

app/views/acts/new.html.erb
<h1>New act</h1>

<%= render 'form' %>

<%= link_to 'Back', acts_path %>

app/views/acts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @act.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @act.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @act.time %>
</p>

<p>
  <strong>Performers:</strong>
  <% @act.performers.each do|performer| %>
  <ul>
  <li><%= performer.name %></li>
  </ul>
  <% end %>
</p>

<%= link_to 'Edit', edit_act_path(@act) %> |
<%= link_to 'Back', acts_path %>

app/views/dashboard/index.html.erb
<h1>Listing acts</h1>


<% @acts.each do |act| %>
  <h3><%= act.name %></h3>
  <% act.performers.each do |performer| %>
    <ul>
      <li><%= performer.name %> <td><%= link_to 'Move', move_performer_path(performer) %></td></li>
    </ul> 
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AmoebaCircusOnRailsRuby003</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to 'Acts', acts_path %> | <%= link_to 'Performers', performers_path %> |
  <%= link_to 'Dashboard', index_path %>

<%= yield %>

</body>
</html>

app/views/performers/_form.html.erb
<%= form_for(@performer) do |f| %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :talent %><br>
    <%= f.text_field :talent, {:value => (@performer.talent.name if @performer.talent)}  %> 
  </div>

  <div class="field">
    <%= f.label :generation_number %><br>
    <%= f.number_field :generation_number %>
  </div>

  <% Act.all.each do |a| %>
  <div class="checkbox"> 
    <%= check_box_tag('act[]', a.id, a.performers.include?(@performer), :id => a.name ) %>
    <%= label_tag a.name %>
  </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/performers/edit.html.erb
<h1>Editing performer</h1>

<%= render 'form' %>

<%= link_to 'Show', @performer %> |
<%= link_to 'Back', performers_path %>

app/views/performers/index.html.erb
<h1>Listing performers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Talent</th>
      <th>Generation number</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @performers.each do |performer| %>
      <tr>
        <td><%= performer.name %></td>
        <td><%= performer.talent.name if performer.talent%></td>
        <td><%= performer.generation_number %></td>
        <td><%= link_to 'Show', performer %></td>
        <td><%= link_to 'Edit', edit_performer_path(performer) %></td>
        <td><%= link_to 'Split', split_performer_path(performer) %></td>
        <td><%= link_to 'Destroy', performer, :method => :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Performer', new_performer_path %>

app/views/performers/move.html.erb
  <h1>Change the Act for <%= @performer.name if @performer %> </h1>

  <%= form_tag move_performer_path do %> 

  <% Act.all.each do |a| %>
  <div class="checkbox"> 
    <%= check_box_tag('act[]', a.id, a.performers.include?(@performer), :id => a.name ) %>
    <%= label_tag a.name %>
  </div>
  <% end %>

  <div class="actions">
    <%= submit_tag "Update" %>
  </div>
  <% end %>

app/views/performers/new.html.erb
<h1>New performer</h1>

<%= render 'form' %>

<%= link_to 'Back', performers_path %>

app/views/performers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @performer.name %>
</p>

<p>
  <strong>Talent:</strong>
  <%= @performer.talent.name %>
</p>

<p>
  <strong>Generation number:</strong>
  <%= @performer.generation_number %>
</p>

<p>
  <strong>Acts:</strong>
  <% @performer.acts.each do |act| %>
  <ul>
  <li><%= act.name %></li>
  </ul>
  <% end %>
</p>

<%= link_to 'Edit', edit_performer_path(@performer) %> |
<%= link_to 'Back', performers_path %>